name: CD

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: "0 8 * * *"
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test
        run: git tag -n
      - name: Generate Tag List
        run: git tag -n > ${{ runner.temp }}/template-tag.txt

      - name: Update Template Tag list Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ runner.temp }}/template-tag.txt
          name: "Template Tag List"
          body: "Release to maintain template tag list."
          token: ${{ secrets.token }}
          tag: "qweqwe"
          allowUpdates: true